function F = seficiencialaboral(l0, k0, k1, A, alpha, delta, gamma, z)
    F = ((1-alpha)*(((exp(z))*(k0^alpha)*(l0^(1-alpha)))/l0)) - ...
        gamma*((exp(z)*(k0^alpha)*(l0^(1-alpha)))-(k1-(1-delta)*k0)) / ...
        ((1-gamma)*(1-l0));
end